### ISSUE TITLE
Create the Plex Pin Auth Package

### ISSUE THREAD

**Issue by harrisonhoward** [harrisonhoward/plex_pin_auth#1]
## Task

Create the package `plex_pin_auth`. This package will need to make HTTP requests to the Plex API to generate a token specific to the user.

## Methods

_May need a util function for making a request_
- `get_pin` Requests to get the pin
- `get_token` Returns the token from a pin (Unless the pin hasn't been activated yet)

## Documentation

[get-pin](https://plexapi.dev/docs/plex/get-pin)
[get-token](https://plexapi.dev/docs/plex/get-token)

## Requirements

- Automatically ping `get_token` until the token is completed
- Token retrieving times out after 15 minutes
- Support CLI for verification of functionality
- Optionally create tests, this may not be possible due to the impossibility of testing `get_token`. But we need ` setInternval` so not so impossible.

**Comment by harrisonhowardax** [comment]
Completed in #2 and #4
